CREATE DATABASE EMPLOYEEEES;

USE EMPLOYEEEES;


CREATE TABLE EMPLOYE(
ID INT  primary key auto_increment NOT NULL,
NAME varchar (100),
SALARY int);
drop table EMPLOYE;
INSERT INTO EMPLOYE VALUES(NULL,"MUNEEB",50000);
INSERT INTO EMPLOYE VALUES(NULL,"MALAIKAH",16000);
INSERT INTO EMPLOYE VALUES(NULL,"LAMIA",40000);
INSERT INTO EMPLOYE VALUES(NULL,"ROMAN",38000);
INSERT INTO EMPLOYE VALUES(NULL,"SAAD", 35000);
INSERT INTO EMPLOYE VALUES(NULL,"YANISH",18000);
INSERT INTO EMPLOYE VALUES(NULL,"YOSUF",31000);
INSERT INTO EMPLOYE VALUES(NULL,"KHUZIMA",300000);
INSERT INTO EMPLOYE VALUES(NULL,"SHOAIB",26000);
INSERT INTO EMPLOYE VALUES(NULL,"HASSAN",10000000);

SELECT * FROM EMPLOYE;

SELECT NAME , SALARY,
case
when SALARY>=30000 THEN "BEST EMPLOYEEE"
WHEN SALARY>=20000 AND SALARY<=29999 THEN "Normal Employee"
WHEN SALARY>=15000 AND SALARY<=19999 THEN " EMPOLYEEE"
else "salary not confirmed" end as "employeee salariess"
from EMPLOYE;

