-- TO CREATE DATABASE
CREATE DATABASE OFFICE;
-- TO USE DATABASE 
USE OFFICE;

-- TO CREATE TABLE  
CREATE TABLE ONE (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(200),
    CLASS VARCHAR(200),
    AGR INT,
    SALARY VARCHAR(250)
);

-- TO SELECT FROM TABLE 
SELECT 
    *
FROM
    ONE;

-- TO INSERT VALUE IN TABLE ALL COLUMNS WITHOUT COL_NAME

INSERT INTO ONE values(NULL, "YOUSUF", "SQL","13",13.0000000000);
INSERT INTO ONE values(NULL, "MUNEEB", "SQL","13",140.00000000);
INSERT INTO ONE values(NULL, "MALAIKAH", "SQL","13",1.50000000000);
INSERT INTO ONE values(NULL, "SAAD", "SQL","13",100005000.000);
INSERT INTO ONE values(NULL, "KHUZIMA", "SQL","13",15000.0000000);
INSERT INTO ONE values(NULL, "LAMIA", "SQL","13",16000000.00);
INSERT INTO ONE values(NULL, "HAMID", "SQL","13",105500000.0000);
INSERT INTO ONE values(NULL, "SHOAIB", "SQL","13",155000.0000);

/* 1) AGGREGATE FUNCTIONS */
-- TO PERFORM SUM FUNCTION
SELECT 
    SUM(SALARY)
FROM
    ONE;
SELECT 
    SUM(SALARY) AS 'TEACHER SALARIES'
FROM
    ONE;
    
-- TO PERFORM COUNT FUNCTION 
SELECT 
    COUNT(SALARY)
FROM
    ONE;
SELECT 
    COUNT(SALARY) AS 'TEACHER SALARIES'
FROM
    ONE;
    
-- TO PERFORM AVG FUNCTION
SELECT 
    AVG(SALARY)
FROM
    ONE;
SELECT 
    AVG(SALARY) AS 'TEACHER SALARIES'
FROM
    ONE;
    
-- TO PERFORM MAX FUNCTION
SELECT 
    MAX(SALARY)
FROM
    ONE;
SELECT 
    MAX(SALARY) AS 'TEACHER SALARIES'
FROM
    ONE;

-- TO PERFORM MIN FUNCTION
SELECT 
    MIN(SALARY)
FROM
    ONE;
SELECT 
    MIN(SALARY) AS 'MINNIUM SALARY'
FROM
    ONE;

-- TO PERFORM FUNCTION WITH ALL COLUMNS
SELECT 
    *, MIN(SALARY) AS 'EMPLOYEE SALARIES'
FROM
    ONE;

-- TO PERFORM FUNCTION WITH ALL COLUMNS
SELECT 
    *, MAX(SALARY) AS "Maximum Salary" FROM ONE;

/* 2) SCALAR FUNCTIONS */
-- TO PERFORM LOWER FUNCTION WITH SELECTING ALL COLUMNS
SELECT 
    NAME, CLASS, LOWER(CLASS)
FROM
    ONE;
 
-- TO PERFORM LOWER FUNCTION WITH SELECTING SPECIFIC COLUMNS 
SELECT 
     NAME,CLASS,LOWER(NAME) FROM ONE; 
 
-- TO PERFORM UPPER FUNCTION
SELECT 
    *, UPPER(NAME)
FROM
    ONE;


-- TO PERFORM LENGTH FUNCTION
SELECT 
    *, LENGTH(NAME)
FROM
    ONE;


-- TO PERFORM SUBSTRING FUNCTION
SELECT 
    *, SUBSTRING(NAME, 3, 4)
FROM
    ONE;
 
-- TO PERFORM ROUND FUNCTION 
SELECT 
    *, ROUND(SALARY) AS ' ROUND VALUE'
FROM
    ONE;

-- TO PERFORM CURRENT TIMESTAMP FUNCTION 
SELECT CURRENT_TIMESTAMP;

-- TO PERFORM FORMAT FUNCTION
SELECT 
    *, FORMAT(SALARY, 4)
FROM
    ONE;




